### ISSUE TITLE
Maybe you can tell how to train it

### ISSUE THREAD

**Issue by TLZS** [asarigun/TransGAN#1]
Maybe you can tell how to train it,and maybe you can train it with celeb

**Comment by asarigun** [comment]
Hi, thanks for your interest in the repo.  you can find the detailed training process [here](https://github.com/asarigun/TransGAN/blob/main/main.ipynb). For the following versions, I will try to experiment on different datasets as you mentioned and try to get reported metrics in the [paper](https://arxiv.org/abs/2102.07074). If you have any good idea to train faster, please do not hesitate to contact wit me.
