### ISSUE TITLE
Create your own FID stats file

### ISSUE THREAD

**Issue by IlyasMoutawwakil** [asarigun/TransGAN#13]
Hello and thanks for the implementation.
I'm trying to train this model on a different datset, but to do so I need a custom `fid_stats` file for my dataset. How can I create it ?

**Comment by meh-naz** [comment]
Hi I'd like to know how to train this model on my own dataset too..

**Comment by asarigun** [comment]
Hi @IlyasMoutawwakil, @meh-naz,

Sorry for the late answer. I haven't used any custom image dataset, but you can follow this [pull](https://github.com/yang-song/score_sde/pull/5). It seems there is more info on how to do that. I hope that will help you!

Best,
Ahmet
