### ISSUE TITLE
Hello, I can't download the file   fid_stats_cifar10_train.npz that you provided in readme! 

### ISSUE THREAD

**Issue by RSMung** [asarigun/TransGAN#8]
Is there any other way to get your pre-trained model?
Thanks.

**Comment by asarigun** [comment]
Hi @RSMung,

Thank you so much interest in the repo! For the pre-trained model, you can follow the #4 issue.

To download the  **fid_stats_cifar10_train.npz** file,  you can use the following command:

```bash
wget http://bioinf.jku.at/research/ttur/ttur_stats/fid_stats_cifar10_train.npz 
```
I hope this will help you!
